### ISSUE TITLE
Desabilitar as opção EDIT PROFILE

### ISSUE THREAD

**Issue by mfnunes** [EDUCACAO-LIVRE/DSpace#13]
Texto original: Desabilitar as opções:  MY DSPACE, RECEIVE EMAIL UPDATES  e EDIT PROFILE
(a funcionalidade "Editar Perfil" ocorre no Portal Educação Livre)

![13](https://cloud.githubusercontent.com/assets/6783589/13225575/358d2392-d96c-11e5-98f3-9011f9ebf75d.png)

Imagem inline 2 - ISSO eu Vou Discutir - Retirar apenas o EDIT PROFILE

**Comment by miltonshintaku** [comment]
ok, acho que tb fechou
