### ISSUE TITLE
Tornar a caixa de texto para pesquisas ("Buscar no repositório") visível de forma automática e padrão

### ISSUE THREAD

**Issue by mfnunes** [EDUCACAO-LIVRE/DSpace#14]
atualmente é necessário uma ação do usuário, clicando no ícone para consulta.
![14](https://cloud.githubusercontent.com/assets/6783589/13225518/fd63be4a-d96b-11e5-81e7-6f237b2840c4.png)

**Comment by ricardosgit** [comment]
Eu vi isso no documento. Como agora ele já é visível automaticamente, devido a outra solução, achei um problema de UX deixar duas caixas visíveis. Por esta razão, realizei a outra alteração e esta deixei oculto necessitando o clique. Caso seja para deixar as duas visíveis gentileza confirmar (acho que milton).
!!!

**Comment by ricardosgit** [comment]
Me refiro a caixa de busca grande que foi colocada sempre no início do conteúdo:
![captura de tela 2016-02-25 as 19 49 33](https://cloud.githubusercontent.com/assets/1812690/13337278/432c737e-dbf9-11e5-9fca-5b8d90e3076a.png)

**Comment by mfnunes** [comment]
Eu acho que realmente não precisa as duas. O que tu acha @miltonshintaku?

**Comment by miltonshintaku** [comment]
acho que essa fechou
