### ISSUE TITLE
Posicionar a caixa de texto para pesquisas ("Buscar no repositório") logo abaixo do ícone do Colabore

### ISSUE THREAD

**Issue by mfnunes** [EDUCACAO-LIVRE/DSpace#15]
![15](https://cloud.githubusercontent.com/assets/6783589/13225486/d4d5d99a-d96b-11e5-91d7-b6fac81d642d.png)

**Comment by ricardosgit** [comment]
Já foi realizado e está em produção.
Hoje eu subi alterações que corrige erros para diferentes visualizações de tela e mobile.
![captura de tela 2016-02-25 as 19 49 33](https://cloud.githubusercontent.com/assets/1812690/13337215/ec05573c-dbf8-11e5-92b9-0d36c0bfe2d5.png)

**Comment by mfnunes** [comment]
Está feito de acordo com o solicitado!
