### ISSUE TITLE
Atualizar os metadados do perfil (p1, p2, p3, etc) com as respectivas descrições dos perfis (arquivo previamente encaminhado por e-mail pelo Rafael Lacerda)

### ISSUE THREAD

**Issue by mfnunes** [EDUCACAO-LIVRE/DSpace#16]
![16](https://cloud.githubusercontent.com/assets/6783589/13225409/85195fb2-d96b-11e5-927b-761136e4420a.png)

onde se lê p1 deveria ser, por exemplo, P1 DL -  Domínio de diferentes linguagens verbais e não verbais (língua portuguesa, matemática, corporal, artística, tecnológica e científica), em contextos pessoais, sociais e laborais.
E assim sucessivamente para cada perfil.

**Comment by miltonshintaku** [comment]
Rodrigo.... Por favor, resolva essa pendenga

**Comment by rodrigodba** [comment]
UPDATE metadatavalue SET text_value = 'P1 DL -  Domínio de diferentes linguagens verbais e não verbais (língua portuguesa, matemática, corporal, artística, tecnológica e científica), em contextos pessoais, sociais e laborais.  (COMPARTILHE)' WHERE metadata_field_id = 136 AND text_value LIKE 'p1';

UPDATE metadatavalue SET text_value = 'P2 DLP - Domínio de conhecimentos básicos da língua portuguesa e compreensão de seu uso em contextos pessoais, sociais e laborais. (COMPARTILHE)'  WHERE metadata_field_id = 136 AND text_value LIKE 'p2';

UPDATE metadatavalue SET text_value = 'P3 DMAT - Domínio de conhecimentos matemáticos básicos e compreensão de seu uso em contextos pessoais, sociais e laborais. (COMPARTILHE)'  WHERE metadata_field_id = 136 AND text_value LIKE 'p3';

UPDATE metadatavalue SET text_value = 'P5 CF - Apropriação de conceitos fundamentais de diversas áreas do conhecimento para compreender fenômenos e para aplicar criticamente no mundo do trabalho. (COMPARTILHE)'  WHERE metadata_field_id = 136 AND text_value LIKE 'p5';

UPDATE metadatavalue SET text_value = 'P7 ETIC - Postura ética, reflexiva e crítica nas ações e relações sociais e profissionais. (INSPIRE)'  WHERE metadata_field_id = 136 AND text_value LIKE 'p7';
