### ISSUE TITLE
Em função do contraste de cores, não é possível ler com facilidade a mensagem com fonte  em branco

### ISSUE THREAD

**Issue by mfnunes** [EDUCACAO-LIVRE/DSpace#20]
em algumas situações a mensagem é apresentada com destaque no fundo

**Comment by rodrigodba** [comment]
Qual mensagem? Milton, o Ricardo ainda está no projeto?

**Comment by miltonshintaku** [comment]
sim, tem que combinar o que tem relação com o Ricardo e trabalhar juntos

**Comment by mfnunes** [comment]
![20-1](https://cloud.githubusercontent.com/assets/6783589/13225308/05830578-d96b-11e5-805a-d029bfa832ad.png)
destaque no fundo:
![20-2](https://cloud.githubusercontent.com/assets/6783589/13225307/057c7e38-d96b-11e5-8d00-4b60e4a136d1.png)

**Comment by ricardosgit** [comment]
Arrumei já última leva.
