### ISSUE TITLE
Erro ao clicar em RSS

### ISSUE THREAD

**Issue by mfnunes** [EDUCACAO-LIVRE/DSpace#23]
![23](https://cloud.githubusercontent.com/assets/6783589/13225662/8a396d42-d96c-11e5-99e3-45c4d73a00d6.png)

Ao clicar surge a mensage: 
 Surge a mensagem de erro abaixo:

This XML file does not appear to have any style information associated with
it. The document tree is shown below.
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-
ns#" xmlns="http://purl.org/rss/1.0/" xmlns:dc="http://purl.org/dc/ele
ments/1.1/">
<channel rdf:about="http://200.130.8.94/educacaolivre_ui/handle/123456
789/1101">
<title>DSpace Collection:</title>
<link>
http://200.130.8.94/educacaolivre_ui/handle/123456789/1101
</link>
...

**Comment by ricardosgit** [comment]
Este link está fora para mim. Entretanto, acessei uma coleção e funcionou.
Já foi arrumado? Algum link atualizado para testar?
![captura de tela 2016-02-25 as 19 44 50](https://cloud.githubusercontent.com/assets/1812690/13337091/613e6026-dbf8-11e5-9a36-c4ed75a79eec.png)

**Comment by miltonshintaku** [comment]
http://colabore.educacaolivre.org.br/handle/avante/1102
quando clica no rss aparece uma XML

**Comment by mfnunes** [comment]
Está correto, pois o RSS é um xml, então, quem interpreta ele é o coletador, no caso está sendo aberto no navegador, por isso aparece somente o xml.
