### ISSUE TITLE
Ao nagevar a url está sendo trocada por ip e porta

### ISSUE THREAD

**Issue by mfnunes** [EDUCACAO-LIVRE/DSpace#24]
http://200.130.8.94:8080/handle/123456789/1110

**Comment by rodrigodba** [comment]
Isso provavelmente acontece porque o e-print foi cadastrado quando o servidor não respondia pela 80, só pela 8080. Então ficou gravado dessa forma, quando se clica ele replica.

Uma possível solução seria fazer um update no banco. Ou gerar novos dados, já que é teste mesmo.

**Comment by miltonshintaku** [comment]
veja se consegue ver isso no banco e corrija por favor

**Comment by rodrigodba** [comment]
Corrigido. Para todas as situações.

Para o caso específico fica:
http://200.130.8.94/handle/avante/1110
