### ISSUE TITLE
Meu espaço dá em tela em branco

### ISSUE THREAD

**Issue by miltonshintaku** [EDUCACAO-LIVRE/DSpace#29]
Pessoal, ao se identificar e clicar em meu espaço dá em uma tela em branco

**Comment by ricardosgit** [comment]
Por aqui funciona, veja o print. Entretanto, já foi alterado o layout administrativo, conforme segundo print, e está no git aguardando subir para produção.

![captura de tela 2016-02-25 as 19 41 17](https://cloud.githubusercontent.com/assets/1812690/13337014/e6c59e4a-dbf7-11e5-8336-78ec4e614705.png)
![captura de tela 2016-02-25 as 19 42 03](https://cloud.githubusercontent.com/assets/1812690/13337015/e6c893b6-dbf7-11e5-9475-3360e65e9199.png)

**Comment by mfnunes** [comment]
Já foi resolvido. A interface do administrador já está no ar também.
