### ISSUE TITLE
Geralmente quando algum usuário se loga, no cabeçalho aparece: logado como xxxxx@xxxxx. Isso não está acontecendo, como se o usuário não estivesse logado

### ISSUE THREAD

**Issue by mfnunes** [EDUCACAO-LIVRE/DSpace#3]

**Comment by ricardosgit** [comment]
Está resolvido já na versão atual, pode fechar.
![captura de tela 2016-02-25 as 19 59 20](https://cloud.githubusercontent.com/assets/1812690/13337466/544a5d78-dbfa-11e5-907b-6767fc878c03.png)
