### ISSUE TITLE
o logo (rosinha) deve enviar para a página inicial

### ISSUE THREAD

**Issue by miltonshintaku** [EDUCACAO-LIVRE/DSpace#32]
Ricardo, o logo deve enviar para a página inicial e isso não está sendo feito

**Comment by rodrigodba** [comment]
Não seria uma duplicata do #5 ?

**Comment by mfnunes** [comment]
@miltonshintaku é o logo é esse? Se for pode fechar a issue porque eu já arrumei.
![logo](https://cloud.githubusercontent.com/assets/6783589/13353079/8b10c7cc-dc70-11e5-9eff-94a747ba4e16.jpg)
