### ISSUE TITLE
Ao clicar no logo do banco de conteúdos deveria voltar para página inicial

### ISSUE THREAD

**Issue by mfnunes** [EDUCACAO-LIVRE/DSpace#33]
Tem um problema de navegação, pois ao efetuar uma busca o usuário é redirecionado para a página de resultado e não consegue voltar para a página inicial, pois se clica no logo da página vai para o portal e se clica no logo do banco de conteúdos apenas recarrega a página.

**Comment by rodrigodba** [comment]
Esse issue não seria o mesmo do #32 ?

**Comment by mfnunes** [comment]
É a mesma #5, já foi resolvida!
