### ISSUE TITLE
Os usuários não estão sendo reconhecidos no DSpace em relação às suas permissões.

### ISSUE THREAD

**Issue by mfnunes** [EDUCACAO-LIVRE/DSpace#4]
Ao se logar no portal e ir para o DSpace, aparentemente ocorre a identificação, mas não reconhece as suas permissões

**Comment by miltonshintaku** [comment]
Creio que isso está arrumado, mas quando o ricardo arrumar a interface damos o finalizado

**Comment by miltonshintaku** [comment]
fechado
